### ISSUE TITLE
Add option to ignore untracked files in unstaged changes panel

### ISSUE THREAD

**Issue by rht** [extrawurst/gitui#1156]
**Is your feature request related to a problem? Please describe.**
I'm a `tig` user evaluating alternatives. In `tig`, by default, only unstaged tracked files are shown in the view. With `gitui`, it's rather noisy. I have files like benchmark/profile log output that I produce quickly, and usually don't bother to add into .gitignore.

**Describe the solution you'd like**
Would be nice if there is a config option for this.

**Comment by kosayoda** [comment]
Tangentially related, since currently there is no way to tell the *application* to not show untracked files by default, you have two options:

1. Set [status.ShowUntrackedFiles](https://git-scm.com/docs/git-config#Documentation/git-config.txt-statusshowUntrackedFiles) in your system, global, or local Git Configuration.
2. Manually set the app to not show untracked files each time you launch it: Open the options menu (key is `o` by default), then change `Show untracked` to `No`

**Comment by extrawurst** [comment]
@kosayoda that’s exactly the status quo. Storing your options per repo is spmething we will eventually add

**Comment by extrawurst** [comment]
Storing these options per repo is implemented on master
