### ISSUE TITLE
Search branch

### ISSUE THREAD

**Issue by Wyfy0107** [extrawurst/gitui#1350]
**Is your feature request related to a problem? Please describe.**
When viewing all the branches in gitui, I would like to have the ability to search through these branches

**Describe the solution you'd like**
Perhaps in the branch view, press `/` to start searching, similar to vim

**Describe alternatives you've considered**

**Additional context**

**Comment by extrawurst** [comment]
would be nice to reuse the fuzzy search popup we have for this already (see the file tab)

**Comment by Wyfy0107** [comment]
Haven't used rust yet, but can I try to add this feature ?

**Comment by ObiWanRohan** [comment]
I'm trying my hand at this.

**Comment by ObiWanRohan** [comment]
@extrawurst I have added a key ("Branch Find Toggle") which would toggle the focus to the find box in the branch list popup.
Pressing the key (Currently `/` by default) would shift the focus to the text input.
I didn't go the route of making it similar to the file finder, as there are no other possible inputs in the file finder. Here there are possible inputs like `c` for create branch, `r` for rename and so on.
Otherwise there would have to be a completely separate finder popup for the branches (this is also an option).

Some feature questions come to mind:
- What should be the scope of the finder? (Just the open tab or both tabs). The open tab is easier to implement as it needs lesser changes. 
- Should the matches be highlighted or should only the matches be shown?
- How does the user exit the find mode? (The Escape key or backspacing the whole input)

I'll add more as they come.

**Comment by ObiWanRohan** [comment]
@extrawurst Pinging for answers
