### ISSUE TITLE
The character to represent the action in the UI shortcuts are displayed erroneously. [Windows]

### ISSUE THREAD

**Issue by Andres6936** [extrawurst/gitui#1354]
**Describe the bug**
The character to represent the action in the UI shortcuts are displayed erroneously in Windows.

**To Reproduce**

1. Download the binary for Windows
2. Open gitui

**Screenshots:**

![image](https://user-images.githubusercontent.com/18540634/191808496-64e7cbfb-1160-44b8-9bc9-d7aa1e0d3d23.png)

The same if execute the program with Powershell:

![image](https://user-images.githubusercontent.com/18540634/191808661-f4875dee-e294-4634-bedf-e9136534fc15.png)

**Context (please complete the following information):**
Using Windows 10 21H1

**Comment by AntoniosBarotsis** [comment]
Hello! This is because you are using a font that does not include these glyphs, Gitui works fine for me in Powershell 
![image](https://user-images.githubusercontent.com/50240570/193419947-2f393f13-0226-4eb0-b90a-99e644cb1e9b.png)

I am using [this](https://github.com/eliheuer/caskaydia-cove) font.

This is not a bug.

**Comment by Andres6936** [comment]
@AntoniosBarotsis You are right, I close issue

![image](https://user-images.githubusercontent.com/18540634/193421024-7303adee-802b-43ab-afc5-66f66e2f5c93.png)
