### ISSUE TITLE
`test_visualize_newline` fails on Rust 1.70 nightly

### ISSUE THREAD

**Issue by cruessler** [extrawurst/gitui#1644]
**Describe the bug**

There is an issue in `test_visualize_newline` on Rust 1.70.0-nightly (23ee2af2f 2023-04-07). The root cause seems to be [this call][text-styled] to `Text::styled` in `get_draw_text`. The argument passed to `Text::styled` causing the error to occur is `"↵\n\r"`.

`Text::styled` calls `Text::raw` which calls `content.lines()`. `"↵\n\r".lines()` returns `[ "↵", "", ]` on Rust 1.68 while it returns `[ "↵", "\r", ]` on Rust 1.70.0-nightly (23ee2af2f 2023-04-07).

[text-styled]: https://github.com/extrawurst/gitui/blob/76258fbb933befd697edafb781d8301c220192a8/src/components/textinput.rs#L264-L269

**To Reproduce**

1. Run `rustup override set nightly`
2. Run `cargo test test_visualize_newline`
3. The test fails on Rust 1.70.0-nightly (23ee2af2f 2023-04-07), but not on Rust 1.68

**Expected behavior**

The test passes.

**Context:**

- OS/Distro + Version: all OSes that run nightly on CI except Linux ARM

**Comment by pm100** [comment]
Just spent a long time investigating this. It is due to this change

https://github.com/rust-lang/rust/commit/cef81dcd0a9503ff8a8f915c43688a78c1c11d83

it changes how this string `"\u{21b5}\n\r"` is parsed by `lines`

it used to end up as Spans with `->` (the little return arrow and `""` ie empty

it is now parsed to `->` (the little return arrow and `"\r"` ie empty

This is because lines is documented as splitting on \n or \r\n. It used to also delimit on \n\r. Now 'fixed' so that the latter is parsed as one new line plus a spare \r

**Comment by pm100** [comment]
PR => https://github.com/extrawurst/gitui/pull/1646

**Comment by extrawurst** [comment]
This is a super weird change. Was wondering where this came from! Thanks guys for looking into this
