### ISSUE TITLE
Ability to view large commit messages in log

### ISSUE THREAD

**Issue by werman** [extrawurst/gitui#181]
**Is your feature request related to a problem? Please describe.**

I'm dealing with git repositories which have large commit messages, e.g. https://gitlab.freedesktop.org/mesa/mesa/-/commit/797fa87ec9891384fee7588fda36c80dfed1a39d, no matter how big I make the tui - commit message would not be fully visible.

**Describe the solution you'd like**
**Describe alternatives you've considered**

Two solutions comes to mind:
- Be able to focus "Message" window and scroll it with arrows
- Have a hotkey to open the message "full-screen" with arrows scrolling

**Comment by extrawurst** [comment]
@werman thanks for your interest in gitui. that actually makes sense, sometimes found myself scaling the terminal font to be able to read big-ass messages that are used in some repos 🙈

**Comment by cruessler** [comment]
@extrawurst If this is not yet taken, I’d give it a try! Do you have a specific solution in mind?

**Comment by extrawurst** [comment]
@cruessler nice! Feel free to take it but I think this one is actually more involved, because I think the best solution is to allow switching focus between the message and the file tree (when in the fullscreen commit-detail view only)  via `arrow-up` and `down`. 
this is the preferred solution to having a dedicated new hotkey to switch to the message.

once the message is focused `arrow-up`/`down` scrolls it.

so the problem with that solution is that we need to know when the bottom of the message is reached and a next `arrow-down` will switch focus again back down to the filetree. the paragraph drawing in `tui-rs` only takes a `scroll` as integer and for the `message` drawing we use is doing the word-wrap internally without a channel back to us to know how many lines there are to scroll. 

There is some investigation needed, maybe `tui-rs` stateful-drawing presents a solution or the line-wrapping part can be exposed to access it or (most involved) we need to implement our own line-wrapped-drawing of the message.

But of course I might be missing something and there is an elegant solution here that I am missing :)

**Comment by extrawurst** [comment]
Here is a open ticket basically about the lack such a feature in tui-rs: https://github.com/fdehau/tui-rs/issues/89

**But** the last commenter basically provides a solution feasible for us: using `textwrap` crate to manually do the word wrapping and draw it using non-wrap paragraph. This way we know the number of lines upfront and know the bounds for the scrolling.

See https://github.com/mgeisler/textwrap (but no fancy hyphenation feature please)

Soo @cruessler wanna go for it?

**Comment by extrawurst** [comment]
@cruessler hey man anything I can help you with here to get this out the door?

**Comment by cruessler** [comment]
@extrawurst Thanks for asking! I was busy preparing a talk, but since that's done now, I want to finish the PR this weekend. I'll let you know if I run into trouble!

**Comment by cruessler** [comment]
@extrawurst A good chunk of the work is done. I expect to be able to update the PR in the next few days.
