### ISSUE TITLE
Add inverted colors mode for light backgrounds

### ISSUE THREAD

**Issue by piegamesde** [extrawurst/gitui#28]
**Is your feature request related to a problem? Please describe.**

Currently the main text color is yellow. Which doesn't read well on a white terminal background.

**Describe the solution you'd like**

A CLI flag to switch to a dark color theme for better readability.

**Describe alternatives you've considered**

- I don't know if it's a good idea, but simply inverting all colors might be enough
- Full blown (custom) theme support
- An environment variable or a configuration file are viable alternatives to CLI flags

**Additional context**

![image](https://user-images.githubusercontent.com/14054505/79915322-0c1c6580-8427-11ea-806f-47fd71b3222e.png)

**Comment by extrawurst** [comment]
Hm that is a more complicated issue. But it is definitely important to find a solution for that since everyone uses different colorsets - so it is essential that the solution scales

**Comment by extrawurst** [comment]
Similar but less challenging than #57:

1. refactor all `Style` objects that are generated on the fly all over the place to be statics first, because that allows us to figure out what are the common ones and derive the *theme* of `gitui`
2. introduce a new struct `Theme` that holds values for all these values 
3. initialise this default Theme to look like it is right now
4. use `crossterm` feature `serde` allowing us to save/load it
5. load the theme on startup if the file exists / dump the theme to file to make sure changes are reflected (additions)

**Comment by MCord** [comment]
I am going to try to refactor the code and let you know how it goes.

**Comment by extrawurst** [comment]
see https://github.com/extrawurst/gitui/pull/65
