### ISSUE TITLE
Thoughts on checking `~/.confg/gitui` or `$XDG_CONFIG_HOME/gitui` on mac before defaulting to the existing dir?

### ISSUE THREAD

**Issue by nerdrew** [extrawurst/gitui#317]
Many terminal apps use `~/.config/<app-name>` even on mac. I assume other also have `~/.confg` (or `$XDG_CONFIG_HOME/`) checked into VCS somewhere. It'd be nice to have my gitui config live with all my other terminal app configs :)

Happy to open a PR if this is welcome.

**Comment by extrawurst** [comment]
I would need more input from more Mac users on this. 
@jonstodle what are your 2c on this?

**Comment by jonstodle** [comment]
I honestly expect terminal apps to put config in either `~/` directly or (preferably) in `~/.config/<app name>`. Logs and temp files I still expect to be put in their idiomatic macOS locations.

**Comment by terhechte** [comment]
Very longtime Mac user here; I was puzzled to find that the configuration resides in `~/Library..` as that is normally reserved for non-terminal GUI apps. Terminal apps nowadays prefer `~/.config` (compared to the `~/.` that used to be the default aeons ago)

**Comment by extrawurst** [comment]
I love it, special treatment everywhere... so we can use `.config` on macOS without any conditions?

**Comment by non-descriptive** [comment]
looks like [XDG](https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x) directories are conventional just among devs, otherwise it should fallback to recommended [apple fs guide](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1).

**Comment by shawnohare** [comment]
I symlink most of my configs with a stow-like bash script, and greatly appreciate apps that use XDG on Unix-like systems so that my my linking is consistent across OSes. The vast majority of the apps I use follow XDG, but there's a few outliers that prove annoying when I have to use a mac (e.g., for work).
