### ISSUE TITLE
support https push via credentials dialog

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#344]
right now only ssh push works really smooth.
https-repos will not know what pwd to use in the least and if the checkout url did not contain the username it will also not be found.

we should try to query the username from git-config and open username input if not, afterwards lets open another input for the pwd. in this first iteration let's not worry about storing any of this.

to keep things simple lets reuse `TextInputComponent` we already have even for password in a first iteration and not worry about exchanging everything with `*`. Let's use two popups in a row for *username* and *password* so we can easily adjust for when a username can be found and only ask for the password then.

see also #304

**Comment by alocquet** [comment]
If you want, I can also take this one.

**Comment by extrawurst** [comment]
Sure 👍

**Comment by pm100** [comment]
I did some investigation and gitui really should integrate with the git credential manager that stores creds securely on each platform. That's how the git vscode plugins work and how the git command line works. Prompting for password should be a last resort

**Comment by alocquet** [comment]
In fact, retrieving credentials from git credential manager is very easy (3 lines of code).

Asking password is harder because we need to show a textinput when we are in git2 credential callback, ie in `asyncgit::sync::remotes::remote_callbacks`.

I don't know what is the best way to do this : 
* check credentials before calling `asyncgit::push` to be able to ask password in PushComponent... 
* raise an error in git2 credential callback (`asyncgit::sync::remotes::remote_callbacks`), manage this error in PushComponent (ie : ask password in a textinput) and finally retry `asyncgit::push` with user credentials.
* I had also the idea to give a callback from PushComponent to `asyncgit::push` function, but this callback will be used int git2 credential callback (`asyncgit::sync::remotes::remote_callbacks`) which can't be wainting user input.
I don't know if I am intelligible :roll_eyes:

**Comment by WizardOhio24** [comment]
Surely the first option you mention is the best, if the repo is cloned by https(which you could get using the remote ref of the branch(i.e if it starts with https:// ...)), get the necessary credentials before, first by checking the credential manager and then if any are missing with textboxes, then push.

**Comment by extrawurst** [comment]
@pm100 do you mind looking into #353 to see if this allows you to push to the repo you had problems with?

**Comment by extrawurst** [comment]
> @extrawurst sure, - i might need instructions on how to get that PR into my fork ( not a git* wizard)

https://stackoverflow.com/a/36629277/2458533
