### ISSUE TITLE
Use more navigation keys

### ISSUE THREAD

**Issue by data-man** [extrawurst/gitui#43]
**Is your feature request related to a problem?**
Use Home, End, PgUp and PgDn keys in diff and log panes.

**Describe the solution you'd like**
Scroll to top, bottom and by screen's height.

**Describe alternatives you've considered**
E.g. like tig.

**Comment by extrawurst** [comment]
Hi @data-man thanks for your interest in the project! Thats indeed a great idea. Haven't thought of it since I am on a small laptop keyboard ;D

**Comment by bobismijnnaam** [comment]
This issue seems relevant to my request, so I will post it here instead of making a new issue if that is okay.

Any plans to support h, j, k, l for navigation? Some sites (i.e. duckduckgo) also support this natively, and as a vim user support would be nice. (I do not think any other vim bindings should be added, as that's way too opinionated. But basic hjkl support would be nice).

In any case, thanks for making gitui. Been using it for a bit and works nice and fast!

**Comment by extrawurst** [comment]
> Any plans to support h, j, k, l for navigation? Some sites (i.e. duckduckgo) also support this natively, and as a vim user support would be nice. (I do not think any other vim bindings should be added, as that's way too opinionated. But basic hjkl support would be nice).

I am really not a fan of duplicating functionality 🤔- My main concern is simplicity - I need to think about this.

> In any case, thanks for making gitui. Been using it for a bit and it works nice and fast!

Thank you so much❤️

**Comment by data-man** [comment]
@extrawurst 
> support home/end to jump up/down

Thank you for getting started!
I tested this commit, but the `Home` and `End` aren't working.

**Comment by extrawurst** [comment]
> I tested this commit, but the `Home` and `End` aren't working.

Thanks so much for even trying a build from code!😍
Hooked up my external keyboard now and fixed It 🙈
see https://github.com/extrawurst/gitui/commit/5fc8d72ed65b4f64733419566dfd0798d235aab4

home/end were easy, the remaining ones (pages/down) will take little longer, since I need to rework some code to allow this. (currently the *rendering* is IMGUI style and stateless, so I dont know how high the screen area is outside the rendering code. I will figure this out since I could use it for a couple of other things too!

**Comment by extrawurst** [comment]
@data-man if you want to try the page up/down should now work in the commit log 😊

**Comment by data-man** [comment]
@extrawurst Great! Thank you!

Also would be nice to add mouse wheel support in the future.

**Comment by extrawurst** [comment]
home/end/pageUp/pageDown support released as `0.2.3`: https://github.com/extrawurst/gitui/releases/tag/v0.2.3
