### ISSUE TITLE
[Feature request] clone git shell default commit message template

### ISSUE THREAD

**Issue by Berjou** [extrawurst/gitui#517]
**Problem**

I'm working on some project with strict commit messages style requiering me to list all the files that have been modified, added, deleted in the current commit. Fortunately, this is really easy to do when using the `git commit` command, which opens the `.git/COMMIT_EDITMSG` file, in which each files to be committed are listed, and a lot of other info like the diff, etc... are already listed in comments. Unfortunately, `gitui` does not use this file but seems to use a hardcoded `$HOME/config/gitui/COMMITMSG_EDITOR`.

Is there any reason here to not follow the same behavior as the `git commit` command?

**Suggested solution**

When opening the editor when committing with `gitui`, `$GIT_DIR/COMMIT_EDITMSG` should be used, to follow the same behavior as the original `git commit` command.

**Comment by extrawurst** [comment]
@Berjou I looked into this and the problem is that we do not use the git shell commands. it seems the git shell creates this default commit message when you `git commit`.

One option would be to trying to mimic the same behaviour and repopulating the commit msg.

Also what I found is that you can actually overwrite this default behaviour in git shell using the `commit.template` config. we also do not support this currently but that should be easy

**Comment by Berjou** [comment]
Thank you for your interest in this feature.

I think I understand correctly the problem and I that it is not that easy to copy the git shell behavior without actually using it, but I still think that it would be a great feature to have.
