### ISSUE TITLE
GitUI does not work under ConEmu

### ISSUE THREAD

**Issue by balokir** [extrawurst/gitui#577]
I'm run gutui from cmd console or from FAR in ComEmu - app started, empty black window shown. The single allowed action - break it by Ctrl-C.
gitui 0.12.0 (installed by choco)
conemu 161206 stable
Windows7

**Comment by asmwarrior** [comment]
Hi, I have the same issue. I'm on Windows 7.
I just download the latest official ConEmu(210304, from [Download ConEmu latest release](https://www.fosshub.com/ConEmu.html)) and gitui 0.12.0

It just shows a blank window, nothing is shown on the window.

BTW:  [Cmder | Console Emulator](https://cmder.net/) is a ConEmu based shell, and I see gitui works on this shell. But, I always see many unwanted characters(gibberish) shown in the screen.

**Comment by extrawurst** [comment]
Unfortunately I have no access to a windows machine so I need help on this. I would first try to build/run `tui-rs` examples (using crossterm) in *ConEmu* and if that fails aswell go one level deeper and run the `crossterm` examples to narrow down where the issue comes from.

**Comment by extrawurst** [comment]
so I now installed windows in a VM and tried this and it works for me with gitui `0.12` (installed via choco):
<img width="606" alt="image" src="https://user-images.githubusercontent.com/776816/111036592-394b7b00-8420-11eb-93a8-57bf1ef93564.png">

windows 10
conemu 210312 [64]

**Comment by asmwarrior** [comment]
Hi, [extrawurst](https://github.com/extrawurst), you may look at the bottom of your screen shot, the icon after the "Stage Item" and the "Reset Item" does not shown correctly.

In my Windows 7 Simplified Chinese Edition, I have to change the encoding to GB2312 in the setting of the ComEmu to fix this issue(The default encoding is the "default" in the list). But if I change the encoding, the boarder will also be changed, which is not as good as the boarder when the encoding is "default".

**Comment by extrawurst** [comment]
> you may look at the bottom of your screen shot, the icon after the "Stage Item" and the "Reset Item" does not shown correctly.

yes but that is quiet some other issue than the title suggests which I deem way less important than "it does not work"

**Comment by asmwarrior** [comment]
I have recorded a screen cast(a gif file) about the issue when I try to start gitui under ConEmu,  and I have reported it to ConEmu's issue, see here: [ComEmu can't shown the gitui's main window, but Cmder can · Issue #2297 · Maximus5/ConEmu](https://github.com/Maximus5/ConEmu/issues/2297)

**Comment by asmwarrior** [comment]
> 
> 
> I have recorded a screen cast(a gif file) about the issue when I try to start gitui under ConEmu, and I have reported it to ConEmu's issue, see here: [ConEmu can't shown the gitui's main window, but Cmder can · Issue #2297 · Maximus5/ConEmu](https://github.com/Maximus5/ConEmu/issues/2297)
I have updated that issue by more information, and it looks like another git cmd tool `lazygit` works inside the standalone ConEmu.

**Comment by Etherian** [comment]
I still experience this issue and am unable to use GitUI due to it.

**Comment by extrawurst** [comment]
> I still experience this issue and am unable to use GitUI due to it.

Hoping any windows jokey will come along also caring for this to actually tackle it 👍

**Comment by Etherian** [comment]
I found a solution/workaround to this issue. Setting the `TERM` environment variable to any value allows GitUI's interface to be displayed on ConEmu/Cmder. The interface doesn't always display *correctly*, and it will still sometimes clobber the buffer instead of restoring it, but those seem to be separate issues.

Is there a good place to document this fix?

**Comment by extrawurst** [comment]
@Etherian does it work better than on my [screenshot](https://github.com/extrawurst/gitui/issues/577#issuecomment-798579652) ? care to share a screenshot ?

to what did you set the `TERM` env variable?

**Comment by Etherian** [comment]
GitUI works as below with `TERM` set to "cygwin", "xterm", "supercalifragilistic", or " ".

![gitui_issue_2](https://user-images.githubusercontent.com/14620634/127381334-e4891341-650c-4b07-928d-2d54a9d21efd.jpg)
Notice how the hotkey bar is doubled and the rest of the interface is offset up by a line.

![gitui_issue_3](https://user-images.githubusercontent.com/14620634/127381524-6fb74080-5e79-4313-b6f9-9f1c088a15e7.jpg)
Switching to another tab garbles the interface.

![gitui_issue_4](https://user-images.githubusercontent.com/14620634/127381907-534803ef-9103-48cd-8681-2a27b51f02ee.jpg)
The garbling seems to be related to the hotkey bar collapsing behind `more [.]` , since the interface renders perfectly when the window is wide enough to accommodate every hotkey. Also, refreshing the interface by changing the height of the window will fix the garbling on tabs where `more [.]` isn't shown, and switching to a tab with `more [.]` garbles the interface again.
