### ISSUE TITLE
consolidate CredComponent

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#588]
right now we have 3 places using `CredComponent`. 
each use their individual instance so they do not share once typed-in credentials.

we should consolidate these into a single popup which stores and reuses its inputs (a popup similar to the `TagCommitComponent`

**Comment by sum12** [comment]
`TagCommitComponent` does not return anything however `CredComponent` needs to "return"  a creds object. So I dont see a way to return anything once an event the to show the `CredComponent` has been added to the `queue` (like `TagCommit`).

Also since each of the 3 have their own copy of `CredComponent` they can call `set_cred` but once `CredComponent` is pulled out of these 3 components, then they wont be able to call `set_cred` since it will be behind a reference and wont be available `mutably` (unless we want to use `mutex`, which seems complex)

**Comment by sum12** [comment]
how about `RC` like `theme` and `key_config`  ?

**Comment by sum12** [comment]
@extrawurst I made a draft #688. 
let me know if its going in the correct direction.
