### ISSUE TITLE
Doesn't works with SSH for remote(github)

### ISSUE THREAD

**Issue by realtica** [extrawurst/gitui#615]
**Description**

The following error has thrown when I tried to push to remote server (github.com)

`git error:error authenticating: no auth sock variable; class=Ssh (23)`

**Expected behavior**

GIT CLI works fine!

**Context:**
 - Linux/Debian
 - gitui 0.13.0
 - rustc 1.51.0 (2fd73fabe 2021-03-23)

**Comment by savchenko** [comment]
Can't reproduce. Which Debian version? Have you tried pre-compiled binary from GH? Are you using `ssh-agent`? If yes, please provide details of the agent setup.

**Comment by irmantas** [comment]
I have similar issues with private gitlab instance, cannot pull/push over SSH (git@my.private-gitlab.com:group/repository-name.git).
CLI works fine too.
MacOS Big Sur
gitui 0.14.0
installed via brew

**Comment by eriksixt** [comment]
Got a similar problem on macos:
`git remote -v
origin	git@gitlab.com:eriksixt/my-repo.git (fetch)
origin	git@gitlab.com:eriksixt/my-repo.git (push)`

Trying to push via gitui:
`Error
push failed: 
git error:Bad credentials.`

Pushing via git cli works fine.

MacOS Big Sur
gitui 0.14.0
installed via brew

**Comment by arkag** [comment]
Same issue for me. Pushing to a self-hosted gitlab instance over SSH. Using a `cargo install`'d version of gitui on WSL Ubuntu 20.04.

![image](https://user-images.githubusercontent.com/6749810/116305812-86ca4000-a761-11eb-9c94-c9f6c05ca804.png)

**Comment by eriksixt** [comment]
I think we are looking at two different issues here. I figured out my "Bad Credentials" issue on macOS.

Recap:
- Repo was cloned via ssh
- Pulling and pushing works via git cli
- gitui however complains about bad credentials

Turned out it has nothing to do with gitlab in my case. I checked if my private key was loaded correctly into the ssh-agent via `ssh-add -l`. But no keys are loaded. However, git cli keeps working and also ssh access to some remote machines works.

So I found that my ssh config has the following entry:
```
$ cat ~/.ssh/_config
Host *
  UseKeychain yes
```

My private key is protected with a passphrase. Turns out that this passphrase is saved in the macOS keychain. The git cli and other applications seem to be able to pull this passphrase from the Keychain and just use the private key, but gitui is not.

When I load the key into the ssh-agent correctly via `ssh-add` also gitui works as intended.

**Comment by irmantas** [comment]
@eriksixt thanks a lot adding key to ssh-agent fixes `Bad credentials` issue for me too

**Comment by arkag** [comment]
Yep, adding the key to ssh-agent fixed the issue for me as well.

**Comment by extrawurst** [comment]
@realtica how about you?

otherwise I also found something on nodegit (is also based on `libgit2`) that might be relevant: https://github.com/nodegit/nodegit/issues/1085

**Comment by Zeioth** [comment]
Had this issue too. So I thougt, "Ok I'm gonna add my key to the ssh agent every time I launch gitui"

And added this to local/bin

    alacritty -e zsh -c 'ssh-add '~/.ssh/zeioth-github.key'; gitui -d ~/workspaces/myrepo' &

It only works if I call the script from terminal. If I launch it from rofi, it won't ask for the passphrase and will open gitui directly. Any solution for this?

**Comment by Zeioth** [comment]
Ok I fould the next solution:

    alacritty -e zsh -c 'source ~/.zshrc && \
    eval `ssh-agent` \
    eval `keychain --eval --noask ~/.ssh/zeioth-github.key` && \
    ssh-add '~/.ssh/zeioth-github.key'; \
    gitui -d ~/workspaces/myrepo' &

This basically open the ssh-agent, open the keychain for the current terminal session, add the key to the keyring (it will ask for passphrase), and finally launches gitui.

This should be a very secure solution.

**Comment by realtica** [comment]
Thanks, Gitui needs the private key into ssh-agent:
`ssh-add ~/.ssh/id_rsa`
I'll close the issued.
