### ISSUE TITLE
Add a separator to visualize commit message from extended description

### ISSUE THREAD

**Issue by alexherbo2** [extrawurst/gitui#652]
In the log view, we see the following commit message:

```
Update README

Extended description
```

as:

```
Update READMEExtended description
```

It could be nice to render as:

```
Update README┊Extended description
```

**Comment by extrawurst** [comment]
That actually looks like a bug.

**Comment by alexherbo2** [comment]
I liked to see whether a commit had an extended message.  We could easily see references and spot auto-squashed messages.

**Comment by extrawurst** [comment]
@alexherbo2 that would be a new feature, please open a new issue with a suggestion how to indicate that

**Comment by alexherbo2** [comment]
Not sure how it differs from _Add a separator to visualize commit message from extended description_.

I mean I was happy before, just a separator would have been enough. xd

**Comment by extrawurst** [comment]
before #662 it was a bug, I dont know when this was introduced but the expected behaviour was that only the subject line is shown in the commit log. 

what you want is a feature and has less priority and also needs a concept of how to visualise, so its a less low hanging fruit and requires a dedicated issue, which I would label *good first issue* and see if anyone picks it up. if you like feel free to create a PR
