### ISSUE TITLE
Add new line support for multi-line input box

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#711]
this is almost done in #509 by @WizardOhio24 - someone just needs to bring it to the finish line

**Comment by IndianBoy42** [comment]
What is left to do here?

**Comment by WizardOhio24** [comment]
At the moment, the multi-line mostly works, there are a few glitches which need sorting out which can cause the state to become inconsistent, but it mostly works right now (it just doesn't always work).
As well as adding multiline editing, this PR allows the commit box to expand rather than adding a scroll bar immediately and only adds a scroll bar if the commit box is big enough - it is the scrollbar and the scrolling which can cause the inconsistent state (if I remember correctly), the editing and expanding box worked (I think).

Feel free to take it on.  And if you have any questions on the PR, feel free to ask.

**Comment by IndianBoy42** [comment]
I've merged it into my fork to try it, I'll play whack-a-mole with any bugs i see as i use it

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by extrawurst** [comment]
Released in 0.25
