### ISSUE TITLE
commit amend directly in log tab

### ISSUE THREAD

**Issue by parrotdance** [extrawurst/gitui#778]
**Is your feature request related to a problem? Please describe.**

I always type the command `git commit --amend` directly, instead type `git commit` first and considered about "should I add `--amend` flag?". So I think provide "Commit amend" right in status panel (but not in popup panel) will be a nice improvement(at least for me).

**Describe the solution you'd like**

Provide "commit with amend" command right in status panel.

**Describe alternatives you've considered**

btw, there is nothing about "how to make a amend commit" in the help panel, I find the right way but still spend some time to search issues and PRs.

**Comment by extrawurst** [comment]
this is what it is supposed to look like after merging #779 

<img width="711" alt="Screenshot 2021-06-08 at 11 26 40" src="https://user-images.githubusercontent.com/776816/121160462-673c3200-c84c-11eb-809b-fbfe9a51fd6b.png">

**Comment by abergmeier** [comment]
This is especially bad as commit currently is submitted via ENTER.
The numbers I have accidentally submitted a commit is legion.

In all these cases I just want to fix the recent commit - but often cannot because I have no other changes to trigger the commit dialog.

If this really is not possible for default - maybe we could add an extension mechanism for adding commands to screens?
So maybe an yaml file where you write:
```yaml
screens:
  status:
    add_commands:
     - amend
```
