### ISSUE TITLE
Shift+enter to "git add ." in status view

### ISSUE THREAD

**Issue by alistaircarscadden** [extrawurst/gitui#82]
**Describe the solution you'd like**
Would be nice to recreate the add all behaviour with, perhaps, shift+enter.

**Comment by extrawurst** [comment]
hey @alistaircarscadden this is an edgecase where you have a lot of files in the root of your git folder, cause otherwise you can press enter on the folders to quickly stage/unstage a bunch of files.

Right now I will not add another command because the command bar (on the bottom) is getting crowded slowly. I need to first figure out how to handle additional commands 🤔

**Comment by alistaircarscadden** [comment]
Good point. To me, remembering some hotkeys has never been an issue but I do see you've made it your mandate to have all the keys visible in the UI, which is a noble goal.

If it were up to me, Shift is common enough that to me it means "shift+[X] to do task [X] with a greater scope". I'd just have the command available for those who know the key, and have the key written in the documentation. Shift+Enter in [1] view stages all. Shift+C in [2] view stages all and commits (same behaviour as `git commit -a -c <msg>`.

**Comment by extrawurst** [comment]
@alistaircarscadden we definitely need to be able to add more convenience shortcuts and still allow people to get the app without studying manpages. I think @MCord came with a good idea in #83 that allows best of both worlds, you will get your shortcut :)
