### ISSUE TITLE
Create  Fixup Commits

### ISSUE THREAD

**Issue by pe** [extrawurst/gitui#829]
**Is your feature request related to a problem? Please describe.**
Creating a fixup commit is complex. It's not possible only with gitui and possibe but still cumbersome with other tools.

**Describe the solution you'd like**
- stage the changes
- instead of commit I hit the fixup shortcut
- gitui shows the log and I can select the commit I want to fixup
- gitui creates a fixup commit which I can rebase later

**Describe alternatives you've considered**

Using gitui:

- stage the changes
- switch to "log"
- select the commit I want to fixup, copy the hash
- quit gitui
- `git commit --fixup` +  pasted hash

In other git clients (sourcetree, tig) I created an external command `git commit --fixup {SHA}`. Then I

- stage the changes
- switch to the log
- select the commit I want to fixup
- launch my external command.

(I'm open to implement this myself. It would depend on the effort and your willingness to accept it though.)

**Comment by extrawurst** [comment]
related to #32

**Comment by osnyx** [comment]
I'm still dearly missing this, is this blocked by the same missing library functionality as https://github.com/extrawurst/gitui/issues/32#issuecomment-1179526881 ?

**Comment by pbirnzain** [comment]
Same here. I frequently use the amend feature in the commit window.
When I want to fixup an older commit, I usually revert to `git log` and `git commit --fixup` (I tend to forget the hashes immediately, so they have to remain on screen).
Having a fixup command in the log view that helps creating the commit message would already be a major improvement.

**Comment by extrawurst** [comment]
ok if its just about rewording a commit msg we can probbaly easily hack something together. reuse the `CommitComponent` and extend `Mode` with a Fixup variant that take a `CommitId` for input

**Comment by extrawurst** [comment]
@pe still interested to work on that?

**Comment by pe** [comment]
Not really at the moment. Sorry.

**Comment by extrawurst** [comment]
https://github.com/extrawurst/gitui/pull/312 does most of the heavy lifting already

**Comment by pbirnzain** [comment]
I built and tested the new reword feature locally. It's pretty cool, but only part of the solution.

Reword and fixup are the separate two actions an amendment does, the man page for git-commit (--fixup section) explains it quite nicely.

`git commit --amend` and `git commit --fixup=amend:HEAD` provide similar functionality,
the difference being that the --fixup variant can be applied to any commit, and has to be explicitly applied using git rebase --autosquash or git rebase --interactive.

gitui already can do what `git commit --amend` does, and now also `git commit --fixup=reword:<commit>` (but somehow without doing a rebase? Or does this happen implicitly, is this why a clean working tree is needed to reword?).

Unfortunately my Rust skills are very meager so far, so I have a hard time understanding the code, let alone contributing.
The amend mode already seems to take a commit id? Maybe the solution to this is not to far off.

**Comment by extrawurst** [comment]
ok wait so what variants are there:
1. git commit --amend
2. git commit --fixup:amend:HEAD
3. git commit --fixup:reword:<commit>

where we now have 1 and 3 but still miss 2? if so can you explain exactly what it does?

> but somehow without doing a rebase? Or does this happen implicitly, is this why a clean working tree is needed to reword?

no it does rebase, that's why it needs a clean state

**Comment by Mirko-von-Leipzig** [comment]
I think this issue was closed incorrectly and I would love having the feature as originally described here.

I'll give a longer explanation since I think this issue was a bit misunderstood. Apologies if this is unecessary.

Sometimes you'll find yourself wanting to fix issues in your previous commits, but you want to preserve the commit history, at least temporarily, and then later squash these fixes into the original commits they fixed. A good example of this is submitting a PR for review. Its been reviewed and you now want to fix some of the previous commits - however you don't want to rebase as this would mess with anyone doing a 2nd review.

git provides `git commit --fixup=<SHA>` which enables the following workflow. It adds a new commit which is marked with some additional text. This acts like a completely normal commit and can be reviewed as normal. You can repeat this multiple times as you see fit. Once you're happy and you no longer need to conserve history for review purposes you do `git rebase ... --autosquash` which then rebases and squashes each fixup commit into the original target commit.

What would be nice is if gitui enabled doing `git commit --fixup=<SHA>` from its commit menu. As described by OP:

1. Stage changes
2. Move to commit pane
3. Hit fixup shortcut e.g. `Ctrl-f`
4. gitui presents a log view to let us select the target commit (this is much nicer than manually looking for the correct SHA)
5. gitui then executes `git commit --fixup=<SHA>`
