### ISSUE TITLE
[RFC] more commands support

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#83]
*One of the main goals of `gitui` is to not require the user to learn cryptic hotkeys/shortcuts to work with it. The command bar (at the bottom) always shows what actions are available in the current context.*

That said:
Right now, in certain views the command bar is already quiet full and especially crowded when using a small/narrow terminal.

some features right now are not tackled because of this:
* #82 
* #44 
* allowing to commit not only when in the staging area of the status view

one solution for this could be to automatically cut of the commands at the end and show a `more [m]` command that would popup something similar to the help but only with the available commands plus allowing to trigger them when pressing enter on one.

Any better ideas?

**Comment by jugglerchris** [comment]
Rather than listing the commands in full on the command bar, I think it would be fine to just list the keys and rely on the help popup if needed.  So instead of:

```
Focus Stage [2] Stage Item [enter] Reset Item [D] Nav [←↑→↓] Diff [→] Help [h] Quit [ctrl+c] 
```
It could be:
```
[2][enter][D][←↑→↓][^c] Help [h]
```
or something along those lines, maybe grouping the single-character ones together.

**Comment by MCord** [comment]
we have to use colors to comress commands a bit like Norton back in the day:

![image](https://user-images.githubusercontent.com/1547111/82546601-a2dc5f00-9b58-11ea-9652-2eb064b8edcd.png)


what about using sub-menus ? I mean for the less frequently commands instead of running the command we can open a submenu like:

![image](https://user-images.githubusercontent.com/1547111/82546875-1f6f3d80-9b59-11ea-8308-c52a3a37317f.png)

This has the benefit of being self documenting and provides shortcut sequences for power users ?

wdyt ?

**Comment by extrawurst** [comment]
So I gave this a bit more thought. The submenu approach has one drawback: We need a shortcut for every submenu to open to inspect the commands inside, or we need a shortcut that switches focus entirely to the menu structure and then use the arrow-keys to navigate the menu structure.
Both solutions do not feel right.

My idea right now is to keep the bottom-bar as is and cut of commands that do not fit the width. this would automatically add a `more [space]` shortcut at the end to expand the bottom bar to the required height to be able to draw all available commands.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/776816/82731521-d3aec680-9d07-11ea-9e0a-39df3befae64.png">

commands already are sorted based on some sort of `priority` which should allow us to put the most important ones up front.

comments?

**Comment by MCord** [comment]
the problem with having a flat command toolbar is that it gets crowded fast and there is no grouping of related commands. on the other hand this design's is more horizontal which is an added value on  modern screens.

**Comment by ciaranmooney** [comment]
I feel you may have painted yourself into a corner with your first two statements. 

1. _One of the main goals of `gitui` is to not require the user to learn cryptic hotkeys/shortcuts to work with it._ 
2. _The command bar (at the bottom) always shows what actions are available in the current context._

The first is admirable however I believe the second is the root of the issue you are currently experiencing with the design.

It may be possible to add a third (implied) ambition which is also in conflict with the second above.

3. Add more features users find beneficial.

There is limited screen real-estate available and whatever scheme you decide on now (eg, jugglerchris's reasonable suggestion above) will probably eventually hit the same problem as more features/combinations are introduced.

May I suggest re-phrasing your second statement to something more like:

* It should always be easy to determine the correct command.

I would hope that this alternative statement opens up the "idea" space. 

My suggestions would be:

* a scheme where the first letter, or high lighted letter is the associated command key. 
* an easily accessible hint system where a key can be pressed to highlight the command. Such as pressing `alt` when using some GUIs where the shortcut key gains an underline.
* a comprehesive, well laid out help modal.
* a list of the most unused shortcuts at the bottom. The assumption being the user knows the most used because they are using them!

**Comment by extrawurst** [comment]
#101 contains a WIP of my suggested solution (https://github.com/extrawurst/gitui/issues/83#issuecomment-633051728):
![Screenflick Movie 23](https://user-images.githubusercontent.com/776816/83366430-4b878b80-a3af-11ea-8cff-2046ff37b9e9.gif)

After this I am considering adding another option to reduce the commands to the shortcuts-only like @jugglerchris suggested.
